NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

api:
  type : rest
  resource: "@AppBundle/Resources/config/routing.yml"
  prefix : /api/v1
